# SPRING
# ======================================================================================================================


# QA BASE
# ======================================================================================================================
web-application:
  base-url: "https://www.automationexercise.com"
  browser: "chrome"
  browse-window-size: "1920x1080"
  timeout: 10000
  headless: false



# AUTOMATIONEXERCISE COM
# ======================================================================================================================
automationexercise-com:
  user-name: "${AUTOMATIONEXERCISE_USER_NAME}"
  user-email: "${AUTOMATIONEXERCISE_USER_EMAIL}"
  user-password: "${AUTOMATIONEXERCISE_PASSWORD}"